# Generated by Django 4.2.5 on 2023-09-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0002_alter_item_sku"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="phone_number",),
    ]
