# Generated by Django 4.2.5 on 2023-09-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0003_remove_customer_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Car", "Car Delivery"),
                    ("Bopis", "Buy Online Pick Up In Store"),
                    ("Delivery", "Large Delivery"),
                    ("Will Call", "Place Order in store"),
                ],
                default="Will Call",
                help_text="Type of Order",
                max_length=20,
            ),
        ),
    ]
