# Generated by Django 4.2.5 on 2023-09-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0004_order_delivery_date_order_delivery_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="WG444020", max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
