# Generated by Django 4.2.5 on 2023-09-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0005_order_order_number_alter_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=20),
        ),
    ]
