# Generated by Django 4.2.5 on 2023-09-18 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0006_alter_order_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for orders",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(default="H6845-", max_length=20),
        ),
    ]
