# Generated by Django 4.2.5 on 2023-09-18 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0008_alter_order_order_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="order_number",),
    ]
