# Generated by Django 4.2.5 on 2023-09-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0012_alter_order_order_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="order_number", new_name="slug",
        ),
    ]
