# Generated by Django 4.2.5 on 2023-09-19 16:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0014_order_phone_number"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="phone_number",),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="state_code",
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="street",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="zip_code",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
