# Generated by Django 4.2.5 on 2023-09-19 16:27

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0015_remove_order_phone_number_customer_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="customer", name="phone_number",),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=phone_field.models.PhoneField(
                blank=True, help_text="Contact phone number", max_length=31
            ),
        ),
    ]
