# Generated by Django 4.2.5 on 2023-09-20 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0018_remove_order_item_order_item"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="item",),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orderup.item",
            ),
        ),
    ]
