# Generated by Django 4.2.5 on 2023-09-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0019_remove_order_item_order_item"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="item",),
        migrations.AddField(
            model_name="order",
            name="item",
            field=models.ManyToManyField(to="orderup.item"),
        ),
    ]
