# Generated by Django 4.2.5 on 2023-09-21 02:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0020_remove_order_item_order_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="location",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(52),
                ],
            ),
        ),
    ]
