# Generated by Django 4.2.5 on 2023-09-29 18:47

from django.db import migrations, models
import django.db.models.deletion
import orderup.models


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0022_order_quantity"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="quantity",),
        migrations.AlterField(
            model_name="order",
            name="slug",
            field=models.SlugField(
                default=orderup.models.Order.create_random_order, max_length=20
            ),
        ),
        migrations.CreateModel(
            name="Item_set",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="orderup.item"
                    ),
                ),
            ],
        ),
    ]
