# Generated by Django 4.2.5 on 2023-09-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0023_remove_order_quantity_alter_order_slug_item_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product_set",
            field=models.ManyToManyField(to="orderup.item_set"),
        ),
    ]
