# Generated by Django 4.2.5 on 2023-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orderup", "0024_order_product_set"),
    ]

    operations = [
        migrations.RemoveField(model_name="item_set", name="item",),
        migrations.AddField(
            model_name="item_set",
            name="item",
            field=models.ManyToManyField(to="orderup.item"),
        ),
    ]
